# Generated by Django 5.0.3 on 2024-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
